olsrd: configuration sanity checks
* do not start in presence of the old /etc/config/olsrd
* use always use the appropriate IpVersion.

diff --git a/olsrd/files/olsrd.init b/olsrd/files/olsrd.init
--- a/olsrd/files/olsrd.init
+++ b/olsrd/files/olsrd.init
@@ -391,10 +391,6 @@ olsrd_write_olsrd() {
 	[ "$OLSRD_COUNT" -gt 0 ] && return 0
 
 	config_get ipversion "$cfg" IpVersion
-	if [ "$ipversion" = "6and4" ]; then
-		OLSRD_IPVERSION_6AND4=1
-		config_set "$cfg" IpVersion '6'
-	fi
 	config_get smartgateway "$cfg" SmartGateway
 	config_get smartgatewayuplink "$cfg" SmartGatewayUplink
 
@@ -618,9 +614,21 @@ olsrd_update_schema() {
 }
 
 olsrd_write_config() {
-	OLSRD_IPVERSION_6AND4=0
 	OLSRD_COUNT=0
 	config_foreach olsrd_write_olsrd olsrd
+
+	if [ ! -z "$ipversion" ]; then
+	        if [ "$ipversion" = "6and4" ]; then
+		        error "IpVersion 6and4 is no longer supported!"
+			error "You must use /etc/config/olsrd4 for IPv4 and /etc/config/olsrd6 for IPv4"
+		else
+	                error "Option IpVersion is no longer supported!"
+		        error "Please remove it from /etc/config/$UCI_CONF_NAME"
+		fi
+
+		return 1
+	fi
+
 	IPCCONNECT_COUNT=0
 	config_foreach olsrd_write_ipcconnect IpcConnect
 	HNA4_COUNT=0
@@ -746,6 +754,13 @@ olsrd_setup_smartgw_rules() {
 }
 
 start() {
+        if [ -f /etc/config/olsrd ]; then
+	       error "/etc/config/olsrd no longer supported!"
+	       error "please move your config file to /etc/config/olsrd4 and/or /etc/config/olsrd6"
+
+	       return 1
+	fi
+
 	SYSTEM_HOSTNAME=
 	SYSTEM_LAT=
 	SYSTEM_LON=
@@ -770,7 +785,7 @@ start() {
 
 	if [ -z "$OLSRD_CONFIG_FILE" ]; then
 		mkdir -p -- /var/etc/
-		olsrd_write_config > /var/etc/$UCI_CONF_NAME.conf
+		olsrd_write_config > /var/etc/$UCI_CONF_NAME.conf || return 1
 		if [ "$INTERFACES_COUNT" -gt 0 -a "$OLSRD_COUNT" -gt 0 ]; then
 			OLSRD_CONFIG_FILE=/var/etc/$UCI_CONF_NAME.conf
 		fi
@@ -778,53 +793,15 @@ start() {
 
 	[ -z "$OLSRD_CONFIG_FILE" ] && return 1
 
-	local bindv6only='0'
-	if [ "$OLSRD_IPVERSION_6AND4" -ne 0 ]; then
-		bindv6only="$(sysctl -n net.ipv6.bindv6only)"
-		sysctl -w net.ipv6.bindv6only=1 > /dev/null
-		sed -e '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv6
-		sed -e 's/^IpVersion[ ][ ]*6$/IpVersion 4/' -e 's/^\t\t[A-Fa-f0-9.:]*[:][A-Fa-f0-9.:]*[ ][0-9]*$//' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv4
-		rm $OLSRD_CONFIG_FILE
-
-		# some filenames should get the suffix .ipv6
-		for file in $latlon_file $hosts_file $services_file $resolv_file $macs_file $wd_file;do
-			f=$(echo $file|sed 's/\//\\\//g')
-			sed -i "s/$f/$f.ipv6/g" /var/etc/olsrd.conf.ipv6
-		done
-
-		SERVICE_PID_FILE="$PID6"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv6 instance of olsrd running (pid: '$(cat $PID6)'), not starting."
-		else
-			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv6 -nofork
-		fi
-
-		SERVICE_PID_FILE="$PID"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
-		else
-			service_start /usr/sbin/olsrd -f /var/etc/olsrd.conf.ipv4 -nofork
-		fi
-
-		sleep 3
-		sysctl -w net.ipv6.bindv6only="$bindv6only" > /dev/null
-
+	SERVICE_PID_FILE="$PID"
+	if service_check /usr/sbin/olsrd; then
+		error "there is already an instance of $UCI_CONF_NAME running (pid: '$(cat $PID)'), not starting."
+		return 1
 	else
-
-		if [ "$ipversion" = "6" ]; then
-			sed -i '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' "$OLSRD_CONFIG_FILE"
-		fi
-
-		SERVICE_PID_FILE="$PID"
-		if service_check /usr/sbin/olsrd; then
-			error "there is already an IPv4 instance of olsrd running (pid: '$(cat $PID)'), not starting."
-			return 1
-		else
-			service_start /usr/sbin/olsrd -f "$OLSRD_CONFIG_FILE" -nofork
-			service_check /usr/sbin/olsrd || {
-				log "startup-error: check via: '/usr/sbin/olsrd -f \"$OLSRD_CONFIG_FILE\" -nofork'"
-			}
-		fi
+		service_start /usr/sbin/olsrd -f "$OLSRD_CONFIG_FILE" -nofork
+		service_check /usr/sbin/olsrd || {
+			log "startup-error: check via: '/usr/sbin/olsrd -f \"$OLSRD_CONFIG_FILE\" -nofork'"
+		}
 	fi
 
 	olsrd_setup_smartgw_rules
