olsrd: init: verbose logging if daemon-startup fails. till now everything is quiet in this situation. reproduce via configuring httpinfo-plugin on ipv6-socket (which throws an silent error)

diff --git a/olsrd/files/olsrd.init b/olsrd/files/olsrd.init
--- a/olsrd/files/olsrd.init
+++ b/olsrd/files/olsrd.init
@@ -817,8 +817,12 @@ start() {
 			return 1
 		else
 			service_start /usr/sbin/olsrd -f "$OLSRD_CONFIG_FILE" -nofork
+			service_check /usr/sbin/olsrd || {
+				log "startup-error: check via: '/usr/sbin/olsrd -f \"$OLSRD_CONFIG_FILE\" -nofork'"
+			}
 		fi
 	fi
+
 	olsrd_setup_smartgw_rules
 }
 
