kea: fix kea.init error handling
kea.init returned 0 for invalid service names.
Print an error to stderr and return 1 to indicate failure.

Signed-off-by: Liu Yu <f78fk@live.com>

diff --git a/net/kea/files/kea.init b/net/kea/files/kea.init
--- a/net/kea/files/kea.init
+++ b/net/kea/files/kea.init
@@ -29,7 +29,9 @@ start_kea() {
 			cnf="${CONF_PATH}/kea-${name}.conf"
 			;;
 		*)
-			return 0
+			echo "Error: Invalid service name '$name'" >&2
+			return 1
+			;;
 	esac
 
 	procd_open_instance "$name"
