vnstat: run as vnstat user/group & use procd
Run vnstatd as specific user instead of root.  Can no longer stomp on
any directories/files it feels like.  This may help prevent losing data
if vnstat is using custom data directory residing on an as yet unmounted
fs.

Similarly tell vnstatd to not add extra interfaces other than those in
the config file by default

Convert to procd, so gets restarted on failures.

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

diff --git a/net/vnstat/files/vnstat.init b/net/vnstat/files/vnstat.init
--- a/net/vnstat/files/vnstat.init
+++ b/net/vnstat/files/vnstat.init
@@ -1,24 +1,26 @@
 #!/bin/sh /etc/rc.common
 # Copyright (C) 2008-2011 OpenWrt.org
 
-START=99
+START=95
+USE_PROCD=1
+
+CONFIGFILE="/etc/vnstat.conf"
 
 vnstat_option() {
 	sed -ne "s/^[[:space:]]*$1[[:space:]]*['\"]\([^'\"]*\)['\"].*/\1/p" \
-		/etc/vnstat.conf
+		${CONFIGFILE}
 }
 
-start() {
+service_triggers()
+{
+        procd_add_reload_trigger "vnstat"
+}
+
+start_service() {
 	local lib="$(vnstat_option DatabaseDir)"
-	local pid="$(vnstat_option PidFile)"
 
 	[ -n "$lib" ] || {
 		echo "Error: No DatabaseDir set in vnstat.conf" >&2
-		exit 1
-	}
-
-	[ -n "$pid" ] || {
-		echo "Error: No PidFile set in vnstat.conf" >&2
 		exit 1
 	}
 
@@ -65,25 +67,22 @@ start() {
 		config_get lnk "$cfg" symlink
 		config_get backup_dir "$cfg" backup_dir
 		config_list_foreach "$cfg" interface init_iface
+	}
 
-		return 1
+	chown -h vnstat:vnstat ${CONFIGFILE} || {
+		logger -s -t vnstat -p daemon.err "Invalid UID/GID. Aborting startup"
+		exit 1
 	}
 
 	config_load vnstat
 	config_foreach init_ifaces vnstat
 
-	SERVICE_PID_FILE="${pid}"
-	service_start /usr/sbin/vnstatd -d
-}
-
-stop() {
-	local pid="$(vnstat_option PidFile)"
-
-	[ -n "$pid" ] || {
-		echo "Error: No PidFile set in vnstat.conf" >&2
-		exit 1
-	}
-
-	SERVICE_PID_FILE="${pid}"
-	service_stop /usr/sbin/vnstatd
+	procd_open_instance
+	procd_set_param command /usr/sbin/vnstatd --nodaemon --noadd
+	procd_set_param respawn
+	procd_set_param file "${CONFIGFILE}"
+	procd_set_param stdout 1
+	procd_set_param stderr 1
+	procd_set_param user vnstat
+	procd_close_instance
 }
