isc-dhcp: refuse to add empty DHCP range
ipcalc.sh no longer outputs invalid ranges and fails with an error code in
such cases. React to the error.

Signed-off-by: Leon M. Busch-George <leon@georgemail.eu>

diff --git a/net/isc-dhcp/files/dhcpd.init b/net/isc-dhcp/files/dhcpd.init
--- a/net/isc-dhcp/files/dhcpd.init
+++ b/net/isc-dhcp/files/dhcpd.init
@@ -365,6 +365,12 @@ static_hosts() {
 	config_foreach static_host_add host "$@"
 }
 
+eval_ipcalc() {
+	local output
+	output="$(ipcalc.sh "$@")" || return
+	eval "$output"
+}
+
 gen_dhcp_subnet() {
 	local cfg="$1"
 
@@ -438,7 +444,10 @@ dhcpd_add() {
 
 	dhcp_ifs="$dhcp_ifs $ifname"
 
-	eval "$(ipcalc.sh $subnet $start $limit)"
+	if ! eval_ipcalc "$subnet" "$start" "$limit"; then
+		echo "invalid range params: subnet: $subnet start: $start limit: $limit" >&2
+		return 1
+	fi
 
 	config_get netmask "$cfg" "netmask" "$NETMASK"
 	config_get leasetime "$cfg" "leasetime"
