nut: manage logging
NUT (upstream) logging has changed. With the introduction of
NUT_DEBUG_SYSLOG we can set it to "stderr" and have NUT's messages
go to stderr only.

This avoid most duplicate messages when procd sends stderr to syslog.

The reverse (syslog only from NUT) is not a current configuration
option. See the section for NUT_DEBUG_SYSLOG at
https://networkupstools.org/docs/man/nut.conf.html#_directives

This is needed because we use '-FF' so that the daemons remain in the
foreground, which is required for procd to manage them. When using
'-FF' logging behaves differently in NUT than when backgrounded.

Unfortunately, there is still some work to be done upstream to
completely eliminate duplicate messages, so some message continue to
appear twice, though not neccessarily with the same facility.priority.

See also
https://github.com/jimklimov/nut/blob/0c3eed09b89cce1e5c0c65ca03d05b4612371cb8/UPGRADING.adoc#changes-from-282-to-283
and
https://github.com/openwrt/packages/pull/29896#issuecomment-5012737643

Conversely, the log messages the initscripts emit are now configured to
emit only to syslog and not to stderr. This avoids duplicates messages
caused by procd's automatic (not configurable) behaviour of sending
the initscript's stderr to syslog, while preserving the syslogid,
facility and priority we want.

Signed-off-by: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>

diff --git a/net/nut/files/nutshutdown b/net/nut/files/nutshutdown
--- a/net/nut/files/nutshutdown
+++ b/net/nut/files/nutshutdown
@@ -53,7 +53,7 @@ stop_nut_server_instance() {
 	# We're in an emergency shutdown; best effort shutdown and don't block
 	if [ -z "$1" ]; then
 		echo "$MISSING_UPS_INSTANCE_SKIP_MESSAGE" >&2
-		logger -s -t nut-shutdown "$MISSING_UPS_INSTANCE_SKIP_MESSAGE" || true
+		logger -t nut-shutdown "$MISSING_UPS_INSTANCE_SKIP_MESSAGE" || true
 		return 1
 	fi
 	"$NUT_SERVER_INIT" stop "$1" || true
@@ -76,7 +76,7 @@ shutdown_actual_ups() {
 	# with a proper UCI name (should never happen, hence skipping if it does)
 	if ! check_safe_name "$ups"; then
 		echo "$UNSAFE_UPS_INSTANCE_NAME_SKIP_MESSAGE" >&2
-		logger -s -t nut-shutdown "$UNSAFE_UPS_INSTANCE_NAME_SKIP_MESSAGE" || true
+		logger -t nut-shutdown "$UNSAFE_UPS_INSTANCE_NAME_SKIP_MESSAGE" || true
 		return 1
 	fi
 
@@ -138,7 +138,7 @@ do_forced_shutdown() {
 if [ -n "${IPKG_INSTROOT}" ]; then
 	echo "$NOT_A_LIVE_SYSTEM_BAIL_MESSAGE" >&2
 	# Improbable logging will work
-	logger -s -t nut-shutdown "$NOT_A_LIVE_SYSTEM_BAIL_MESSAGE" || true
+	logger -t nut-shutdown "$NOT_A_LIVE_SYSTEM_BAIL_MESSAGE" || true
 	exit 1
 fi
 
@@ -148,7 +148,7 @@ fi
 	# live system) bail with an error.
 	# Logging probably won't work if /lib/functions.sh is not available but try
 	echo "$MISSING_LIB_FUNCTIONS_SH_BAIL_MESSAGE" >&2
-	logger -s -t nut-shutdown "$MISSING_LIB_FUNCTIONS_SH_BAIL_MESSAGE" || true
+	logger -t nut-shutdown "$MISSING_LIB_FUNCTIONS_SH_BAIL_MESSAGE" || true
 	exit 1
 }
 
@@ -184,7 +184,7 @@ elif [ -f "$NUT_KILLPOWER" ]; then
 	DO_KILLPOWER="1"
 	disable_hotplug || true
 	echo "$MISSING_CONFIG_BAIL_MESSAGE" >&2 || true
-	logger -s -t nut-shutdown "$MISSING_CONFIG_BAIL_MESSAGE" || true
+	logger -t nut-shutdown "$MISSING_CONFIG_BAIL_MESSAGE" || true
 
 	remount_filesystems_as_readonly || true
 fi
