strongswan: there's no left/right firewall, etc.
Strongswan allows you to specify an "agnostic" configuration
as left/right and it determines which one it is at runtime
based on things like what local IP matches the left or right
side, etc.  We can't do this with UCI because (a) broadly, it
doesn't follow the UCI model, but (b) more specifically, there
are places where we are already equating "local" to "left",
and "remote" to "right".

Further, how do you specify that the "updown" or "firewall"
scripts are to be run remotely?  That doesn't even make sense.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

diff --git a/net/strongswan/files/ipsec.init b/net/strongswan/files/ipsec.init
--- a/net/strongswan/files/ipsec.init
+++ b/net/strongswan/files/ipsec.init
@@ -19,6 +19,8 @@ STRONGSWAN_VAR_CONF_FILE=/var/ipsec/strongswan.conf
 
 WAIT_FOR_INTF=0
 
+CONFIG_FAIL=0
+
 file_reset() {
 	: > "$1"
 }
@@ -56,6 +58,12 @@ secret_xappend() {
 
 warning() {
 	echo "WARNING: $@" >&2
+}
+
+fatal() {
+	echo "ERROR: $@" >&2
+
+	CONFIG_FAIL=1
 }
 
 is_aead() {
@@ -114,7 +122,7 @@ add_ike_proposal() {
 			warning "Can't have $hash_algorithm with $encryption_algorithm"
 			hash_algorithm=
 		elif [ -z "$prf_algorithm" ]; then
-			warning "PRF algorithm required with AEAD encryption"
+			fatal "PRF algorithm required with AEAD encryption"
 		fi
 	fi
 
@@ -142,7 +150,9 @@ config_conn() {
 	local local_sourceip
 	local local_leftip
 	local local_updown
+	local updown
 	local local_firewall
+	local firewall
 	local remote_subnet
 	local remote_sourceip
 	local remote_updown
@@ -170,7 +180,9 @@ config_conn() {
 	config_get local_sourceip           "$1"           local_sourceip ""
 	config_get local_leftip             "$1"           local_leftip "%any"
 	config_get local_updown             "$1"           local_updown ""
+	config_get updown                   "$1"           updown ""
 	config_get local_firewall           "$1"           local_firewall ""
+	config_get firewall                 "$1"           firewall ""
 	config_get remote_subnet            "$1"           remote_subnet ""
 	config_get remote_sourceip          "$1"           remote_sourceip ""
 	config_get remote_updown            "$1"           remote_updown ""
@@ -192,6 +204,9 @@ config_conn() {
 	config_get local_cert               "$1"           local_cert ""
 	config_get local_key                "$1"           local_key ""
 
+	[ -z "$left_updown" ] && [ -z "$right_updown" ] || fatal "Left/right updown obsoleted; just use 'updown'"
+	[ -z "$left_firewall" ] && [ -z "$right_firewall" ] || fatal "Left/right firewall obsoleted; just use 'firewall'"
+
 	local esp_proposal="$(parse_esp_proposal "$1")"
 
 	[ -n "$local_nat" ] && local_subnet="$local_nat"
@@ -203,8 +218,7 @@ config_conn() {
 	[ -n "$local_sourceip" ] && ipsec_xappend "  leftsourceip=$local_sourceip"
 	[ -n "$local_subnet" ] && ipsec_xappend "  leftsubnet=$local_subnet"
 
-	[ -n "$local_firewall" ] && ipsec_xappend "  leftfirewall=$local_firewall"
-	[ -n "$remote_firewall" ] && ipsec_xappend "  rightfirewall=$remote_firewall"
+	[ -n "$firewall" ] && ipsec_xappend "  leftfirewall=$firewall"
 
 	case "$fragmentation" in
 	yes|accept|force|no)
@@ -252,8 +266,7 @@ config_conn() {
 
 	[ -n "$local_identifier" ] && ipsec_xappend "  leftid=\"$local_identifier\""
 	[ -n "$remote_identifier" ] && ipsec_xappend "  rightid=\"$remote_identifier\""
-	[ -n "$local_updown" ] && ipsec_xappend "  leftupdown=$local_updown"
-	[ -n "$remote_updown" ] && ipsec_xappend "  rightupdown=$remote_updown"
+	[ -n "$updown" ] && ipsec_xappend "  leftupdown=$updown"
 	ipsec_xappend "  type=$type"
 
 	[ -n "$packet_marker" ] && ipsec_xappend "  mark=$packet_marker"
@@ -467,6 +480,11 @@ start_service() {
 	prepare_env
 
 	[ $WAIT_FOR_INTF -eq 1 ] && return
+
+	if [ $CONFIG_FAIL -eq 1 ]; then
+		procd_set_param error "Invalid configuration"
+		return
+	fi
 
 	procd_open_instance
 
