strongswan: add authority section handling
Add support for the new 'authority' uci section type, which generates
global 'authorities/*' entries in the swanctl.conf file.

Each section is translated into one '<name>' authority block using the
following options:

- 'cacert' defines the CA certificate
- 'cert_uri_base' defines the base URI used by the hash and URL
  features
- 'list crl_uri' defines one or more CRL distribution points, emitted
  as 'crl_uris'
- 'list ocsp_uri' defines one or more OCSP responder URIs, emitted as
  'ocsp_uris'

Example uci config:

  config authority 'ca'
      option cacert 'ca.pem'
      list crl_uri 'http://crlca.example/ca.crl'

generates:

  authorities {
      ca {
          cacert = ca.pem
          crl_uris = http://crlca.example/ca.crl
      }
  }

Signed-off-by: Florian Eckert <fe@dev.tdt.de>

diff --git a/net/strongswan/files/swanctl.init b/net/strongswan/files/swanctl.init
--- a/net/strongswan/files/swanctl.init
+++ b/net/strongswan/files/swanctl.init
@@ -433,6 +433,38 @@ config_mschapv2_secret() {
 	swanctl_xappend1 "}"
 }
 
+config_authority() {
+	local conf="$1"
+
+	local cacert
+	local cert_uri_base
+	local crl_uri
+	local ocsp_uri
+
+	config_get cacert "$conf" cacert
+	config_get cert_uri_base "$conf" cert_uri_base
+	config_list_foreach "$conf" crl_uri append_var crl_uri ","
+	config_list_foreach "$conf" ocsp_uri append_var ocsp_uri ","
+
+	if [ -n "$cacert" ]; then
+		[ "$(dirname "$cacert")" != "." ] && {
+			fatal "cacert \'${cacert}\' can't be pathname"
+			return
+		}
+		[ -f "/etc/swanctl/x509ca/${cacert}" ] || {
+			fatal "cacert \'$cacert\' not found"
+			return
+		}
+	fi
+
+	swanctl_xappend1 "$conf {"
+	[ -n "$cacert" ] && swanctl_xappend2 "cacert = $cacert"
+	[ -n "$cert_uri_base" ] && swanctl_xappend2 "cert_uri_base = $cert_uri_base"
+	[ -n "$crl_uri" ] && swanctl_xappend2 "crl_uris = $crl_uri"
+	[ -n "$ocsp_uri" ] && swanctl_xappend2 "ocsp_uris = $ocsp_uri"
+	swanctl_xappend1 "}"
+}
+
 config_connection() {
 	local conf="$1"
 
@@ -868,6 +900,9 @@ prepare_env() {
 	config_foreach config_mschapv2_secret mschapv2_secrets
 	swanctl_xappend0 "}"
 
+	swanctl_xappend0 "authorities {"
+	config_foreach config_authority authority
+	swanctl_xappend0 "}"
 }
 
 reload_service() {
