[package] olsrd.init add virtual interface name
This patch add interface name handling for the NonOlsrIf Option in olsrd init script.
e.g. NonOlsrIf=lan and not NonOlsrIf=eth0

Signed-off-by: Patrick Grimm <patrick@lunatiki.de>

git-svn-id: svn://svn.openwrt.org/openwrt/packages/net/olsrd@22918 3c298f89-4303-0410-b956-a3cf2f4a3e73

diff --git a/files/olsrd.init b/files/olsrd.init
--- a/files/olsrd.init
+++ b/files/olsrd.init
@@ -171,6 +171,19 @@ olsrd_write_plparam() {
 		shift
 		value="$*"
 	fi
+	if [ "$option" = 'NonOlsrIf' ]; then
+		if validate_varname "$value"; then
+			if get_ifname "$value"; then
+				ifname="$IFNAME"
+				echo "Info: mdns Interface '$value' ifname '$ifname' found" 1>&2
+			else
+				echo "Warning: mdns Interface '$value' not found, skipped" 1>&2
+			fi
+		else
+			warning_invalid_value olsrd "$cfg" "NonOlsrIf"
+		fi
+		[ -z "$ifname" ] || value=$ifname
+	fi
 
 	echo -n "${N}${param}PlParam \"$option\" \"$value\""
 
