bsbf-resources: update to GIT HEAD of 2026-05-16
Update bsbf-resources to the GIT HEAD of 2026-05-16.

- files/etc/uci-defaults/99-bsbf-bonding:
  - Do not ever exit non-zero. It prevents the script from being deleted
    after it's run.
  - Fix creating a new wan zone.
  - Do not disable using DNS servers advertised by the ISP. We can now do
    this as we transparently proxy all DNS traffic to Xray which resolves
    queries.

- files/usr/sbin/bsbf-bonding:
  - Attempting to source a file that doesn't exist breaks the rest of the
    script. Therefore, only source /etc/bsbf/bsbf-bonding.conf if it
    exists. Then, print to stderr if the configuration is improper.

Signed-off-by: Chester A. Unal <chester.a.unal@arinc9.com>
(cherry picked from commit 2ca98be404df5e70bd2a622d9494a7d7eb01b37b)
(cherry picked from commit 3435a86672d47b09038e3c042bd72053418d6a32)

diff --git a/net/bsbf-resources/files/etc/uci-defaults/99-bsbf-bonding b/net/bsbf-resources/files/etc/uci-defaults/99-bsbf-bonding
--- a/net/bsbf-resources/files/etc/uci-defaults/99-bsbf-bonding
+++ b/net/bsbf-resources/files/etc/uci-defaults/99-bsbf-bonding
@@ -42,8 +42,8 @@ fi
 # interfaces other than the one used for lan, if there are any.
 final_wan_interfaces="$wan_network_interface $(echo $lan_interfaces | tr ' ' '\n' | grep -v "^$lan_network_interface$")"
 
-# If there are no suitable wan interfaces, exit with code 1.
-[ -z "$(echo "$final_wan_interfaces" | tr ' ' '\n')" ] && exit 1
+# Exit if there are no suitable wan interfaces.
+[ -z "$(echo "$final_wan_interfaces" | tr ' ' '\n')" ] && exit
 
 # Delete existing wan and wan6 networks.
 uci delete network.wan
@@ -56,12 +56,12 @@ if [ -n "$fw_section" ]; then
 # If firewall section for wan doesn't exist, create one.
 else
 	fw_section=$(uci add firewall zone)
-	uci set firewall.@rule[-1].name='wan'
-	uci set firewall.@rule[-1].input='REJECT'
-	uci set firewall.@rule[-1].output='ACCEPT'
-	uci set firewall.@rule[-1].forward='DROP'
-	uci set firewall.@rule[-1].masq='1'
-	uci set firewall.@rule[-1].mtu_fix='1'
+	uci set firewall.@zone[-1].name='wan'
+	uci set firewall.@zone[-1].input='REJECT'
+	uci set firewall.@zone[-1].output='ACCEPT'
+	uci set firewall.@zone[-1].forward='DROP'
+	uci set firewall.@zone[-1].masq='1'
+	uci set firewall.@zone[-1].mtu_fix='1'
 fi
 
 index=1
@@ -73,7 +73,6 @@ for dev in $final_wan_interfaces; do
 	uci set network.wan$index=interface
 	uci set network.wan$index.device="$dev"
 	uci set network.wan$index.proto='dhcp'
-	uci set network.wan$index.peerdns='0'
 	uci set network.wan$index.metric="$index"
 
 	# Add every wan network entry to firewall wan zone.
@@ -81,14 +80,6 @@ for dev in $final_wan_interfaces; do
 
 	index=$((index + 1))
 done
-
-# Configure dnsmasq.
-# As we don't want to use the DNS servers advertised by WANs, set up DNS
-# forwarding. Use 8.8.8.8 and 8.8.4.4.
-uci -q del_list dhcp.@dnsmasq[0].server='8.8.8.8'
-uci -q del_list dhcp.@dnsmasq[0].server='8.8.4.4'
-uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
-uci add_list dhcp.@dnsmasq[0].server='8.8.4.4'
 
 # Configure xray.
 uci set xray.enabled.enabled='1'
@@ -113,5 +104,5 @@ uci set network.@route[-1].table='100'
 # Commit changes.
 uci commit
 
-# Enable bonding.
-bsbf-bonding --enable
+# Enable bonding and ignore the non-zero exit code of bsbf-bonding.
+bsbf-bonding --enable || true
