miniupnpd: rearrange init functions
Arrange start_service and main init functions first

(to merge with prior)

Signed-off-by: Self Hosting Group <selfhostinggroup-git+openwrt@shost.ing>

diff --git a/net/miniupnpd/files/miniupnpd.init b/net/miniupnpd/files/miniupnpd.init
--- a/net/miniupnpd/files/miniupnpd.init
+++ b/net/miniupnpd/files/miniupnpd.init
@@ -7,6 +7,58 @@ USE_PROCD=1
 PROG=/usr/sbin/miniupnpd
 [ -x "$(command -v nft)" ] && FW="fw4" || FW="fw3"
 
+start_service() {
+	upnpd_uci_migration
+	config_load "upnpd"
+	local enabled config_file log_output
+	config_get enabled settings enabled 0
+	config_get config_file settings config_file
+	config_get log_output settings log_output
+	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
+	if [ -n "$config_file" ]; then
+		conf="$config_file"
+	else
+		local tmpconf="/var/etc/miniupnpd.conf"
+		conf="$tmpconf"
+		mkdir -p /var/etc
+		upnpd_generate_config "$tmpconf"
+	fi
+	if [ "$FW" = "fw4" ]; then
+		nft -s -t -n list chain inet fw4 upnp_forward >/dev/null 2>&1 || fw4 reload
+	else
+		iptables -L MINIUPNPD >/dev/null 2>&1 || fw3 reload
+	fi
+
+	procd_open_instance
+	procd_set_param file "$conf" "/etc/config/firewall"
+	procd_set_param command "$PROG"
+	procd_append_param command -f "$conf"
+	[ "$log_output" = "info" ] && procd_append_param command -v
+	[ "$log_output" = "debug" ] && procd_append_param command -d
+	procd_close_instance
+}
+
+stop_service() {
+	if [ "$FW" = "fw3" ]; then
+		iptables -t nat -F MINIUPNPD 2>/dev/null
+		iptables -t nat -F MINIUPNPD-POSTROUTING 2>/dev/null
+		iptables -t filter -F MINIUPNPD 2>/dev/null
+		[ -x /usr/sbin/ip6tables ] && ip6tables -t filter -F MINIUPNPD 2>/dev/null
+	else
+		nft flush chain inet fw4 upnp_forward 2>/dev/null
+		nft flush chain inet fw4 upnp_prerouting 2>/dev/null
+		nft flush chain inet fw4 upnp_postrouting 2>/dev/null
+	fi
+}
+
+service_triggers() {
+	procd_add_reload_trigger "upnpd"
+}
+
+log() {
+	logger -s -p "${2:-daemon.notice}" -t "upnpd" "$1" || echo "upnpd: $1" >&2
+}
+
 is_port_or_range() {
 	[ "$1" = "0" ] && return 1
 	[ "$1" -ge "1" ] 2>/dev/null && [ "$1" -le "65535" ] 2>/dev/null && return 0
@@ -14,6 +66,48 @@ is_port_or_range() {
 	[ "${1%%-*}" -ge "$minport" ] 2>/dev/null && [ "${1%%-*}" -le "65535" ] 2>/dev/null &&
 		[ "${1##*-}" -ge "$minport" ] 2>/dev/null && [ "${1##*-}" -le "65535" ] 2>/dev/null &&
 		[ "${1##*-}" -ge "${1%%-*}" ] 2>/dev/null && return 0 || return 1
+}
+
+upnpd_add_int_network_preset() {
+	local cfg="$1"
+	local interface acl_preset acl_accept_ports acl_reject_ports acl_custom_first
+	config_get interface "$cfg" interface
+	config_get acl_preset "$cfg" acl_preset accept-high-ports
+	config_get acl_accept_ports "$cfg" acl_accept_ports
+	config_get acl_reject_ports "$cfg" acl_reject_ports "21 23 135 137-139 445 3389"
+	config_get acl_custom_first "$cfg" acl_custom_first
+	local device subnet rejectport acceptpresetports acceptport
+	network_get_device device "$interface"
+	network_get_subnet subnet "$interface"
+	if [ "$2" = "precustom" ]; then
+		echo "# Enable internal network $interface ($device) with preset $acl_preset${acl_custom_first:+ and check custom ACL first}"
+		echo "listening_ip=$device"
+		for rejectport in $acl_reject_ports; do
+			is_port_or_range "$rejectport" && echo "deny $rejectport $subnet $rejectport # Reject port $rejectport on $interface" ||
+				log "Invalid port or port range ($rejectport) in acl_reject_ports ignored" daemon.warn
+		done
+	fi
+	if { [ "$2" = "postcustom" ] && [ "$acl_custom_first" = "1" ]; } ||
+		{ [ "$2" = "precustom" ] && [ "$acl_custom_first" != "1" ]; }; then
+		if [ "$acl_preset" = "accept-high-ports" ]; then
+			acceptpresetports="1024-65535"
+		elif [ "$acl_preset" = "accept-high-ports+web" ]; then
+			acceptpresetports="1024-65535 80 443"
+		elif [ "$acl_preset" = "accept-high-ports+web+dns" ]; then
+			acceptpresetports="1024-65535 80 443 53 853"
+		elif [ "$acl_preset" = "accept-all-ports" ]; then
+			acceptpresetports="1-65535"
+		elif [ "$acl_preset" != "none" ] && [ "$acl_preset" != "accept-listed-ports" ]; then
+			log "Invalid preset ($acl_preset) ignored" daemon.warn
+		fi
+		for acceptport in $acceptpresetports $acl_accept_ports; do
+			is_port_or_range "$acceptport" && echo "allow $acceptport $subnet $acceptport # Accept port $acceptport on $interface" ||
+				log "Invalid port or port range ($acceptport) in acl_accept_ports ignored" daemon.warn
+		done
+	fi
+	if [ "$2" = "precustom" ] && [ "$acl_custom_first" != "1" ] && [ "$acl_preset" != "none" ]; then
+		echo "deny 1-65535 $subnet 1-65535 # Reject ACL by default on $interface"
+	fi
 }
 
 upnpd_add_custom_acl_entry() {
@@ -163,100 +257,6 @@ upnpd_generate_config() {
 		echo "deny 1-65535 0.0.0.0/0 1-65535 # Reject ACL by default"
 
 	} >"$1"
-}
-
-stop_service() {
-	if [ "$FW" = "fw3" ]; then
-		iptables -t nat -F MINIUPNPD 2>/dev/null
-		iptables -t nat -F MINIUPNPD-POSTROUTING 2>/dev/null
-		iptables -t filter -F MINIUPNPD 2>/dev/null
-		[ -x /usr/sbin/ip6tables ] && ip6tables -t filter -F MINIUPNPD 2>/dev/null
-	else
-		nft flush chain inet fw4 upnp_forward 2>/dev/null
-		nft flush chain inet fw4 upnp_prerouting 2>/dev/null
-		nft flush chain inet fw4 upnp_postrouting 2>/dev/null
-	fi
-}
-
-start_service() {
-	upnpd_uci_migration
-	config_load "upnpd"
-	local enabled config_file log_output
-	config_get enabled settings enabled 0
-	config_get config_file settings config_file
-	config_get log_output settings log_output
-	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
-	if [ -n "$config_file" ]; then
-		conf="$config_file"
-	else
-		local tmpconf="/var/etc/miniupnpd.conf"
-		conf="$tmpconf"
-		mkdir -p /var/etc
-		upnpd_generate_config "$tmpconf"
-	fi
-	if [ "$FW" = "fw4" ]; then
-		nft -s -t -n list chain inet fw4 upnp_forward >/dev/null 2>&1 || fw4 reload
-	else
-		iptables -L MINIUPNPD >/dev/null 2>&1 || fw3 reload
-	fi
-
-	procd_open_instance
-	procd_set_param file "$conf" "/etc/config/firewall"
-	procd_set_param command "$PROG"
-	procd_append_param command -f "$conf"
-	[ "$log_output" = "info" ] && procd_append_param command -v
-	[ "$log_output" = "debug" ] && procd_append_param command -d
-	procd_close_instance
-}
-
-service_triggers() {
-	procd_add_reload_trigger "upnpd"
-}
-
-log() {
-	logger -s -p "${2:-daemon.notice}" -t "upnpd" "$1" || echo "upnpd: $1" >&2
-}
-
-upnpd_add_int_network_preset() {
-	local cfg="$1"
-	local interface acl_preset acl_accept_ports acl_reject_ports acl_custom_first
-	config_get interface "$cfg" interface
-	config_get acl_preset "$cfg" acl_preset accept-high-ports
-	config_get acl_accept_ports "$cfg" acl_accept_ports
-	config_get acl_reject_ports "$cfg" acl_reject_ports "21 23 135 137-139 445 3389"
-	config_get acl_custom_first "$cfg" acl_custom_first
-	local device subnet rejectport acceptpresetports acceptport
-	network_get_device device "$interface"
-	network_get_subnet subnet "$interface"
-	if [ "$2" = "precustom" ]; then
-		echo "# Enable internal network $interface ($device) with preset $acl_preset${acl_custom_first:+ and check custom ACL first}"
-		echo "listening_ip=$device"
-		for rejectport in $acl_reject_ports; do
-			is_port_or_range "$rejectport" && echo "deny $rejectport $subnet $rejectport # Reject port $rejectport on $interface" ||
-				log "Invalid port or port range ($rejectport) in acl_reject_ports ignored" daemon.warn
-		done
-	fi
-	if { [ "$2" = "postcustom" ] && [ "$acl_custom_first" = "1" ]; } ||
-		{ [ "$2" = "precustom" ] && [ "$acl_custom_first" != "1" ]; }; then
-		if [ "$acl_preset" = "accept-high-ports" ]; then
-			acceptpresetports="1024-65535"
-		elif [ "$acl_preset" = "accept-high-ports+web" ]; then
-			acceptpresetports="1024-65535 80 443"
-		elif [ "$acl_preset" = "accept-high-ports+web+dns" ]; then
-			acceptpresetports="1024-65535 80 443 53 853"
-		elif [ "$acl_preset" = "accept-all-ports" ]; then
-			acceptpresetports="1-65535"
-		elif [ "$acl_preset" != "none" ] && [ "$acl_preset" != "accept-listed-ports" ]; then
-			log "Invalid preset ($acl_preset) ignored" daemon.warn
-		fi
-		for acceptport in $acceptpresetports $acl_accept_ports; do
-			is_port_or_range "$acceptport" && echo "allow $acceptport $subnet $acceptport # Accept port $acceptport on $interface" ||
-				log "Invalid port or port range ($acceptport) in acl_accept_ports ignored" daemon.warn
-		done
-	fi
-	if [ "$2" = "precustom" ] && [ "$acl_custom_first" != "1" ] && [ "$acl_preset" != "none" ]; then
-		echo "deny 1-65535 $subnet 1-65535 # Reject ACL by default on $interface"
-	fi
 }
 
 upnpd_uci_migration() {
