miniupnpd: new/revised UCI options and improve daemon init/config-gen
- Better document and format default `/etc/config/upnpd` UCI config
- Add a `log` function to log and output to stderr, e.g. when service
  is disabled, no external network interface found, unknown ACL preset,
  or with a custom ACL entry with no action set, then all changes via
  LuCI web interface invert the action (as UCI != LuCI default)
- Revise daemon init/config-gen slightly by declare all UCI options
  (incl. boolean) according to the same principle and replace
  `upnpd_write_bool` with `echo_yesno_opt`/`echo_yesno_opt_inverse`
- The following `upnpd` UCI options been added/changed, and the previous
  options are migrated on daemon start:

upnpd.config UCI option      | Change                    | Previous name
-----------------------------|---------------------------|--------------
acl_preset                   | New option added      (1) |
acl_check_custom             | New option added      (1) |
acl_reject_unsafe_ports      | New option added      (2) |
upnp_igd_friendly_name       | New option, router name   |
allow_cgnat_use              | Allow allow-filtered  (3) | use_stun
stun_host                    | Allow port inclusion  (4) |
log_output                   | Allow info log level      |
allow_third_party_mapping=0  | Inverted/extended to PCP  | secure_mode=1
enabled_protocols=upnp-igd   | Combined option           | enable_upnp=1
enabled_protocols=pcp+nat-pmp| Combined option           | enable_natpmp=1
upnp_igd_download            | In kbit/s and renamed (5) | download
upnp_igd_upload              | In kbit/s and renamed (5) | upload
upnp_igd_compat=igdv1        | Renamed/match default (6) | igdv1=1
enabled                      | Match default         (6) |
lease_file                   | Set by default + IPv6 (7) | upnp_lease_file
upnp_igd_http_port           | Renamed, rem. if default  | port
stun_port                    | Removed, included in host |
notify_interval              | Removed if <900s, minimum |

Notes:
1. New options added to select an ACL preset and decide if custom ACL
   should be checked first. Allowed presets:
   accept-high-ports/accept-high-ports+web[+dns]/accept-all-ports
2. Reject unsafe client ports regardless the ACL, defaults to 21 (FTP),
   23 (Telnet), DCE/NetBIOS/SMB (135/137-139/445) and RDP (3389)
3. Allow allow-filtered for IPv4 CGNAT use and migrate option from X-Wrt
   and only use STUN when necessary with a private/CGNAT external IPv4
4. Remove known incompatible STUN servers and set compatible by default
5. Gets converted, config file now defaults to interface link speed
   instead of 8/4 Mbit/s, which is remove on migration
6. Init default now matches UCI/LuCI default of enabled=0 and UCI
   default (current LuCI 24.10: rmempty=false) of upnp_igd_compat=igdv1
7. Configure undocumented daemon option `lease_file6=${lease_file}-ipv6`
   so that active IPv6 port maps are not deleted when daemon restarts,
   e.g. by deleting a port map. Renamed, and removed if UCI default

Corresponding LuCI PR https://redirect.github.com/openwrt/luci/pull/7822

Close: https://redirect.github.com/openwrt/packages/pull/26531
Signed-off-by: Self Hosting Group <selfhostinggroup-git+openwrt@shost.ing>

diff --git a/net/miniupnpd/files/miniupnpd.init b/net/miniupnpd/files/miniupnpd.init
--- a/net/miniupnpd/files/miniupnpd.init
+++ b/net/miniupnpd/files/miniupnpd.init
@@ -42,51 +42,54 @@ conf_rule_add() {
 	echo "$action $ext_start${ext_end:+-}$ext_end $int_addr $int_start${int_end:+-}$int_end #$comment"
 }
 
-upnpd_write_bool() {
-	local opt="$1"
-	local def="${2:-0}"
-	local alt="${3:-$opt}"
-	local val
+echo_yesno_opt() {
+	[ "$2" -eq "1" ] && echo "$1=yes" || echo "$1=no"
+}
 
-	config_get_bool val config "$opt" "$def"
-	if [ "$val" -eq 0 ]; then
-		echo "$alt=no"
-	else
-		echo "$alt=yes"
-	fi
+echo_yesno_opt_inverse() {
+	[ "$2" -eq "1" ] && echo "$1=no" || echo "$1=yes"
 }
 
 upnpd() {
 	config_load "upnpd"
 	local external_iface external_iface6 external_zone external_ip internal_iface
-	local upload download log_output port config_file serial_number model_number
-	local use_stun stun_host stun_port uuid notify_interval presentation_url
-	local upnp_lease_file ipv6_disable
+	local upnp_igd_upload upnp_igd_download log_output upnp_igd_http_port config_file serial_number model_number
+	local allow_cgnat_use stun_host uuid notify_interval presentation_url
+	local lease_file ipv6_disable
+	local enabled_protocols allow_third_party_mapping system_uptime upnp_igd_compat
+	local acl_preset acl_check_custom acl_reject_unsafe_ports upnp_igd_friendly_name
 
 	local enabled
-	config_get_bool enabled config enabled 1
-	[ "$enabled" -eq 0 ] && return 1
+	config_get_bool enabled config enabled 0
+	[ "$enabled" -eq 0 ] && log "Service disabled" && return 0
 
 	config_get external_iface config external_iface
 	config_get external_iface6 config external_iface6
 	config_get external_zone config external_zone
 	config_get external_ip config external_ip
-	config_get internal_iface config internal_iface
-	config_get port config port 5000
-	config_get upload config upload
-	config_get download config download
-	config_get_bool log_output config log_output 0
+	config_get internal_iface config internal_iface lan
+	config_get upnp_igd_http_port config upnp_igd_http_port 5000
+	config_get upnp_igd_upload config upnp_igd_upload
+	config_get upnp_igd_download config upnp_igd_download
+	config_get log_output config log_output
 	config_get config_file config config_file
 	config_get serial_number config serial_number
 	config_get model_number config model_number
 	config_get uuid config uuid
-	config_get use_stun config use_stun 0
-	config_get stun_host config stun_host
-	config_get stun_port config stun_port
+	config_get allow_cgnat_use config allow_cgnat_use 0
+	config_get stun_host config stun_host stun.nextcloud.com
 	config_get notify_interval config notify_interval
 	config_get presentation_url config presentation_url
-	config_get upnp_lease_file config upnp_lease_file
-	config_get ipv6_disable config ipv6_disable 0
+	config_get lease_file config lease_file /var/run/miniupnpd.leases
+	config_get_bool ipv6_disable config ipv6_disable 0
+	config_get enabled_protocols config enabled_protocols all
+	config_get allow_third_party_mapping config allow_third_party_mapping 0
+	config_get_bool system_uptime config system_uptime 1
+	config_get upnp_igd_compat config upnp_igd_compat igdv1
+	config_get acl_preset config acl_preset
+	config_get acl_check_custom config acl_check_custom
+	config_get acl_reject_unsafe_ports config acl_reject_unsafe_ports "21 23 135 137-139 445 3389"
+	config_get upnp_igd_friendly_name config upnp_igd_friendly_name
 
 	local conf ifname ifname6
 
@@ -119,43 +122,56 @@ upnpd() {
 		local tmpconf="/var/etc/miniupnpd.conf"
 		conf="$tmpconf"
 		mkdir -p /var/etc
+		[ "$ifname" = "" ] && log "External network interface not found, not starting" daemon.err && return 0
 
 		{
 		echo "ext_ifname=$ifname"
-		echo "ext_ifname6=$ifname6"
+		[ -n "$ifname6" ] && [ "$ifname" != "$ifname6" ] && echo "ext_ifname6=$ifname6"
 		[ -n "$external_ip" ] && echo "ext_ip=$external_ip"
 
 		local iface
-		for iface in ${internal_iface:-lan}; do
+		for iface in $internal_iface; do
 			local device
-			network_get_device device "$iface" && echo "listening_ip=$device"
+			network_get_device device "$iface" && echo "# Enable internal network $iface ($device)" && echo "listening_ip=$device"
 		done
 
-		config_load "upnpd"
-		upnpd_write_bool enable_natpmp 1
-		upnpd_write_bool enable_upnp 1
-		upnpd_write_bool secure_mode 1
-		upnpd_write_bool system_uptime 1
-		upnpd_write_bool igdv1 0 force_igd_desc_v1
-		upnpd_write_bool use_stun 0 ext_perform_stun
-		upnpd_write_bool ipv6_disable $ipv6_disable
+		{ [ "$enabled_protocols" = "upnp-igd" ] || [ "$enabled_protocols" = "all" ]; } && echo "enable_upnp=yes" || echo "enable_upnp=no"
+		{ [ "$enabled_protocols" = "pcp+nat-pmp" ] || [ "$enabled_protocols" = "all" ]; } && echo "enable_pcp_pmp=yes" || echo "enable_pcp_pmp=no"
+		{ [ "$allow_third_party_mapping" = "0" ] || [ "$allow_third_party_mapping" = "1" ]; } &&
+			echo_yesno_opt_inverse secure_mode "$allow_third_party_mapping" &&
+			echo_yesno_opt pcp_allow_thirdparty "$allow_third_party_mapping"
+		[ "$allow_third_party_mapping" = "upnp-igd" ] && echo "secure_mode=no" && echo "pcp_allow_thirdparty=no"
+		[ "$allow_third_party_mapping" = "pcp" ] && echo "secure_mode=yes" && echo "pcp_allow_thirdparty=yes"
+		echo_yesno_opt system_uptime "$system_uptime"
+		[ "$upnp_igd_compat" = "igdv1" ] && echo "force_igd_desc_v1=yes" || echo "force_igd_desc_v1=no"
+		# Only use STUN when necessary with a private/CGNAT external IPv4
+		local extipv4 extipv4private
+		network_get_ipaddr extipv4 "$ifname"
+		case "$extipv4" in 10.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].* | 192.168.* | 100.6[4-9].* | 100.[7-9][0-9].* | 100.1[0-1][0-9].* | 100.12[0-7].*)
+			extipv4private=1
+			;;
+		esac
+		if [ "$extipv4private" = "1" ] && [ "$allow_cgnat_use" != "0" ] && [ "$external_ip" = "" ]; then
+			[ "$allow_cgnat_use" = "1" ] && echo "ext_perform_stun=yes"
+			[ "$allow_cgnat_use" = "allow-filtered" ] && echo "ext_perform_stun=allow-filtered"
+			# Commented out as using allow-filtered returns a public IPv4, which is required by some clients, and it is also valid
+			# [ "$allow_cgnat_use" = "allow-private-ext-ipv4" ] && external_ip=203.1.2.3
+			echo "ext_stun_host=${stun_host%%:*}"
+			[ "${stun_host%%:*}" != "${stun_host##*:}" ] && echo "ext_stun_port=${stun_host##*:}"
+		fi
+		echo_yesno_opt ipv6_disable "$ipv6_disable"
 
-		[ "$use_stun" -eq 0 ] || {
-			[ -n "$stun_host" ] && echo "ext_stun_host=$stun_host"
-			[ -n "$stun_port" ] && echo "ext_stun_port=$stun_port"
-		}
+		[ -n "$upnp_igd_download" ] && echo "bitrate_down=$((upnp_igd_download * 1000))"
+		[ -n "$upnp_igd_upload" ] && echo "bitrate_up=$((upnp_igd_upload * 1000))"
 
-		[ -n "$upload" ] && [ -n "$download" ] && {
-			echo "bitrate_down=$((download * 1024 * 8))"
-			echo "bitrate_up=$((upload * 1024 * 8))"
-		}
-
-		[ -n "$upnp_lease_file" ] && touch "$upnp_lease_file" && echo "lease_file=$upnp_lease_file"
+		touch "$lease_file" && echo "lease_file=$lease_file"
+		[ "$ipv6_disable" = "0" ] && touch "${lease_file}-ipv6" && echo "lease_file6=${lease_file}-ipv6"
+		[ -n "$upnp_igd_friendly_name" ] && echo "friendly_name=$upnp_igd_friendly_name"
 		[ -n "$presentation_url" ] && echo "presentation_url=$presentation_url"
 		[ -n "$notify_interval" ] && echo "notify_interval=$notify_interval"
-		[ -n "$serial_number" ] && echo "serial=$serial_number"
-		[ -n "$model_number" ] && echo "model_number=$model_number"
-		[ -n "$port" ] && echo "port=$port"
+		echo "serial=$serial_number"
+		echo "model_number=$model_number"
+		echo "http_port=$upnp_igd_http_port"
 
 		[ -z "$uuid" ] && {
 			uuid="$(cat /proc/sys/kernel/random/uuid)"
@@ -163,9 +179,7 @@ upnpd() {
 			uci commit upnpd
 		}
 
-		[ "$uuid" = "nocli" ] || echo "uuid=$uuid"
-
-		config_foreach conf_rule_add perm_rule
+		[ "$uuid" != "nocli" ] && echo "uuid=$uuid"
 
 		if [ "$FW" = "fw4" ]; then
 			#When using nftables configure miniupnpd to use its own table and chains
@@ -175,6 +189,51 @@ upnpd() {
 			echo "upnp_nat_chain=upnp_prerouting"
 			echo "upnp_nat_postrouting_chain=upnp_postrouting"
 		fi
+
+		echo "# ACL: Reject unsafe client ports first"
+		local unsafeport
+		for unsafeport in $acl_reject_unsafe_ports; do
+			if [ "$unsafeport" -ge "1" ] 2>/dev/null && [ "$unsafeport" -le "65535" ] 2>/dev/null ||
+				{ [ "${unsafeport%%-*}" -ge "1" ] 2>/dev/null &&
+					[ "${unsafeport%%-*}" -le "65535" ] 2>/dev/null &&
+					[ "${unsafeport##*-}" -ge "1" ] 2>/dev/null &&
+					[ "${unsafeport##*-}" -le "65535" ] 2>/dev/null &&
+					[ "${unsafeport##*-}" -ge "${unsafeport%%-*}" ] 2>/dev/null
+				}; then
+				echo "deny 1-65535 0.0.0.0/0 $unsafeport # Reject unsafe client port"
+			else
+				log "Unknown port or port range ($unsafeport) in acl_reject_unsafe_ports ignored" daemon.warn
+			fi
+		done
+		[ "$acl_preset" = "" ] || [ "$acl_check_custom" = "first" ] &&
+			echo "# ACL: Check custom ACL entries" && config_foreach conf_rule_add perm_rule
+		if [ "$acl_preset" != "" ]; then
+			echo "# ACL: Add entries for preset $acl_preset${acl_check_custom:+ and check custom ACL $acl_check_custom}"
+			for iface in $internal_iface; do
+				local device subnet
+				network_get_device device "$iface"
+				network_get_subnet subnet "$iface"
+				if [ "$acl_preset" = "accept-high-ports" ]; then
+					echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $iface"
+				elif [ "$acl_preset" = "accept-high-ports+web" ]; then
+					echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $iface"
+					echo "allow 80 $subnet 80 # Accept HTTP port on $iface"
+					echo "allow 443 $subnet 443 # Accept HTTPS port on $iface"
+				elif [ "$acl_preset" = "accept-high-ports+web+dns" ]; then
+					echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $iface"
+					echo "allow 80 $subnet 80 # Accept HTTP port on $iface"
+					echo "allow 443 $subnet 443 # Accept HTTPS port on $iface"
+					echo "allow 53 $subnet 53 # Accept DNS port (Do53) on $iface"
+					echo "allow 853 $subnet 853 # Accept DNS port (DoT/DoQ) on $iface"
+				elif [ "$acl_preset" = "accept-all-ports" ]; then
+					echo "allow 1-65535 $subnet 1-65535 # Accept all ports on $iface"
+				else
+					log "Unknown ACL preset ignored" daemon.warn
+				fi
+			done
+		fi
+		echo "# ACL: Reject ACL by default last"
+		echo "deny 1-65535 0.0.0.0/0 1-65535 # Reject ACL by default"
 
 		} > "$tmpconf"
 	fi
@@ -186,15 +245,14 @@ upnpd() {
 		else
 			iptables -L MINIUPNPD >/dev/null 2>&1 || fw3 reload
 		fi
-	else
-		logger -t "upnp daemon" "external interface not found, not starting"
 	fi
 
 	procd_open_instance
 	procd_set_param file "$conf" "/etc/config/firewall"
 	procd_set_param command "$PROG"
 	procd_append_param command -f "$conf"
-	[ "$log_output" = "1" ] && procd_append_param command -d
+	[ "$log_output" = "info" ] && procd_append_param command -v
+	[ "$log_output" = "debug" ] && procd_append_param command -d
 	procd_close_instance
 }
 
@@ -212,10 +270,143 @@ stop_service() {
 }
 
 start_service() {
+	upnpd_uci_migration
 	config_load "upnpd"
 	config_foreach upnpd "upnpd"
 }
 
 service_triggers() {
 	procd_add_reload_trigger "upnpd"
+}
+
+log() {
+	logger -s -p "${2:-daemon.notice}" -t "upnpd" "$1"
+}
+
+upnpd_uci_migration() {
+	log "Check UCI options in /etc/config/upnpd to be migrated (to v2.0) ..."
+
+	# Rename use_stun -> allow_cgnat_use
+	if uci -q get upnpd.config.use_stun >/dev/null; then
+		log "use_stun -> allow_cgnat_use"
+		uci rename upnpd.config.use_stun="allow_cgnat_use"
+	fi
+
+	# Migrate CGNAT option currently used in X-Wrt (force_forwarding, since 2021) to
+	# allow_cgnat_use=allow-filtered to enable cross-project migration
+	if uci -q get upnpd.config.force_forwarding >/dev/null; then
+		log "force_forwarding=1 -> allow_cgnat_use=allow-filtered: Migrate CGNAT option"
+		if [ "$(uci -q get upnpd.config.force_forwarding)" = "1" ]; then
+			uci set upnpd.config.allow_cgnat_use="allow-filtered"
+		fi
+		uci delete upnpd.config.force_forwarding
+	fi
+
+	# Remove known incompatible (not CGNAT filtering test capable) STUN servers and include stun_port in stun_host
+	if uci -q get upnpd.config.stun_host | grep -q -E "stun[0-9]?.l.google.com|stun.cloudflare.com"; then
+		log "stun_host: Incompatible STUN server ($(uci -q get upnpd.config.stun_host)) found, remove to set default"
+		uci delete upnpd.config.stun_host
+		uci -q delete upnpd.config.stun_port
+	elif uci -q get upnpd.config.stun_port >/dev/null; then
+		if uci -q get upnpd.config.stun_host >/dev/null &&
+			[ "$(uci -q get upnpd.config.stun_port)" != "3478" ]; then
+			log "stun_port: Include stun_port in stun_host, and remove old option"
+			uci set upnpd.config.stun_host="$(uci -q get upnpd.config.stun_host | cut -d ":" -f 1):$(uci -q get upnpd.config.stun_port)"
+		fi
+		uci delete upnpd.config.stun_port
+	fi
+
+	# Migrate log_output=1 -> log_output=debug: Now info also allowed
+	if uci -q get upnpd.config.log_output >/dev/null; then
+		[ "$(uci -q get upnpd.config.log_output)" = "1" ] &&
+			log "log_output=1 -> log_output=debug: Now info also allowed" &&
+			uci set upnpd.config.log_output="debug"
+		[ "$(uci -q get upnpd.config.log_output)" = "0" ] &&
+			uci set upnpd.config.log_output="default"
+	fi
+
+	# Migrate secure_mode=1 -> allow_third_party_mapping=0: Invert/extend to PCP
+	if uci -q get upnpd.config.secure_mode >/dev/null; then
+		log "secure_mode=1 -> allow_third_party_mapping=0: Invert/extend to PCP"
+		if [ "$(uci -q get upnpd.config.secure_mode)" = "0" ]; then
+			uci set upnpd.config.allow_third_party_mapping="1"
+		else
+			uci set upnpd.config.allow_third_party_mapping="0"
+		fi
+		uci delete upnpd.config.secure_mode
+	fi
+
+	# Migrate download/upload -> upnp_igd_download/upnp_igd_upload: Convert to kbit/s
+	if uci -q get upnpd.config.download >/dev/null; then
+		download="$(uci -q get upnpd.config.download)"
+		if [ "$download" != "1024" ] && [ "$download" -ge "1" ] 2>/dev/null; then
+			log "download -> upnp_igd_download: Convert to kbit/s"
+			upnp_igd_download="$((download * 8 * 1000 / 1024))"
+			uci set upnpd.config.upnp_igd_download="$upnp_igd_download"
+		fi
+		uci delete upnpd.config.download
+	fi
+	if uci -q get upnpd.config.upload >/dev/null; then
+		upload="$(uci -q get upnpd.config.upload)"
+		if [ "$upload" != "512" ] && [ "$upload" -ge "1" ] 2>/dev/null; then
+			log "upload -> upnp_igd_upload: Convert to kbit/s"
+			upnp_igd_upload="$((upload * 8 * 1000 / 1024))"
+			uci set upnpd.config.upnp_igd_upload="$upnp_igd_upload"
+		fi
+		uci delete upnpd.config.upload
+	fi
+
+	# Migrate enable_upnp/enable_natpmp -> enabled_protocols: Combined option
+	if uci -q get upnpd.config.enable_upnp >/dev/null || uci -q get upnpd.config.enable_natpmp >/dev/null; then
+		log "enable_upnp/enable_natpmp -> enabled_protocols: Combined option"
+		if [ "$(uci -q get upnpd.config.enable_upnp)" != "0" ] && [ "$(uci -q get upnpd.config.enable_natpmp)" = "0" ]; then
+			uci set upnpd.config.enabled_protocols="upnp-igd"
+		elif [ "$(uci -q get upnpd.config.enable_natpmp)" != "0" ] && [ "$(uci -q get upnpd.config.enable_upnp)" = "0" ]; then
+			uci set upnpd.config.enabled_protocols="pcp+nat-pmp"
+		elif [ "$(uci -q get upnpd.config.enable_upnp)" = "0" ] && [ "$(uci -q get upnpd.config.enable_natpmp)" = "0" ]; then
+			uci set upnpd.config.enabled="0"
+		fi
+		uci -q delete upnpd.config.enable_upnp
+		uci -q delete upnpd.config.enable_natpmp
+	fi
+
+	# Migrate igdv1=1 -> upnp_igd_compat=igdv1: Extensible/clearer
+	if uci -q get upnpd.config.igdv1 >/dev/null; then
+		log "igdv1=1 -> upnp_igd_compat=igdv1"
+		if [ "$(uci -q get upnpd.config.igdv1)" = "1" ]; then
+			uci set upnpd.config.upnp_igd_compat="igdv1"
+		else
+			uci set upnpd.config.upnp_igd_compat="igdv2"
+		fi
+		uci delete upnpd.config.igdv1
+	fi
+
+	# Rename upnp_lease_file -> lease_file: To original daemon name, and remove if UCI default
+	if uci -q get upnpd.config.upnp_lease_file >/dev/null; then
+		if [ "$(uci -q get upnpd.config.upnp_lease_file)" = "/var/run/miniupnpd.leases" ]; then
+			log "upnp_lease_file -> lease_file: Remove option as UCI default is set"
+			uci delete upnpd.config.upnp_lease_file
+		else
+			log "upnp_lease_file -> lease_file"
+			uci rename upnpd.config.upnp_lease_file="lease_file"
+		fi
+	fi
+
+	# Rename port -> upnp_igd_http_port: Remove if UCI default
+	if uci -q get upnpd.config.port >/dev/null; then
+		if [ "$(uci -q get upnpd.config.port)" = "5000" ]; then
+			log "port -> upnp_igd_http_port: Remove option as UCI default is set"
+			uci delete upnpd.config.port
+		else
+			log "port -> upnp_igd_http_port"
+			uci rename upnpd.config.port="upnp_igd_http_port"
+		fi
+	fi
+
+	# Migrate notify_interval <=900s: Remove to set minimum of 900 (default)
+	[ "$(uci -q get upnpd.config.notify_interval)" -le "900" ] 2>/dev/null &&
+		log "notify_interval <=900s: Remove to set minimum of 900 (default)" &&
+		uci delete upnpd.config.notify_interval
+
+	uci commit upnpd >/dev/null
 }
