miniupnpd: new/updated custom ACL UCI options and migrate section
- Note that the custom ACL is now rejected by default, if it is alone
  used, with no preset or listed accepted ports. Add (ignored) custom
  ACL template entries on migration
- Migrate custom ACL entries to the new section name `acl_entry`
- The following custom ACL UCI options been added or changed, and the
  previous options are migrated on the service restart:

acl_entry UCI options       | Change                     | Previous name
----------------------------|----------------------------|--------------
action                      | New/updated values     (1) |
int_port                    | Remove colon separator (2) | int_ports
ext_port                    | Remove colon separator (2) | ext_ports
descr_filter                | New option             (3) |

1. Allow ignore, and update action option to use the nftables terms
   (allow/deny -> accept/reject). To avoid adding inverted actions when
   changing via LuCI, ensure any missing are set, as LuCI and UCI had
   not matching action defaults. Missing actions are now ignored/logged
2. Ensure that the hyphen (-) is only used as a port range separator by
   migration, as the colon (:) is not valid in LuCI
3. Add missing UCI option to set a regular expression to check for a
   UPnP IGD IPv4 port map description, and fix the current collision
   with the comment field which was not noticed due to a daemon bug
   https://redirect.github.com/openwrt/packages/pull/24495
   https://redirect.github.com/miniupnp/miniupnp/pull/853

Code refactoring:
- Add a more universal usable `is_port_or_range` function instead of
  `upnpd_get_port_range` and check if it has a valid range, and removes
  a shellcheck warning
- Rename `conf_rule_add` function to `upnpd_add_custom_acl_entry`

Signed-off-by: Self-Hosting-Group <selfhostinggroup-git+openwrt@shost.ing>

diff --git a/net/miniupnpd/files/miniupnpd.init b/net/miniupnpd/files/miniupnpd.init
--- a/net/miniupnpd/files/miniupnpd.init
+++ b/net/miniupnpd/files/miniupnpd.init
@@ -7,38 +7,34 @@ USE_PROCD=1
 PROG=/usr/sbin/miniupnpd
 [ -x "$(command -v nft)" ] && FW="fw4" || FW="fw3"
 
-upnpd_get_port_range() {
-	local var="$1"; shift
-	local val
-
-	config_get val "$@"
-
-	case "$val" in
-		[0-9]*[:-][0-9]*)
-			export -n -- "${var}_start=${val%%[:-]*}"
-			export -n -- "${var}_end=${val##*[:-]}"
-		;;
-		[0-9]*)
-			export -n -- "${var}_start=$val"
-			export -n -- "${var}_end="
-		;;
-	esac
+is_port_or_range() {
+	[ "$1" = "0" ] && return 1
+	[ "$1" -ge "1" ] 2>/dev/null && [ "$1" -le "65535" ] 2>/dev/null && return 0
+	[ "$2" = "port0inrange" ] && local minport=0 || local minport=1
+	[ "${1%%-*}" -ge "$minport" ] 2>/dev/null && [ "${1%%-*}" -le "65535" ] 2>/dev/null &&
+		[ "${1##*-}" -ge "$minport" ] 2>/dev/null && [ "${1##*-}" -le "65535" ] 2>/dev/null &&
+		[ "${1##*-}" -ge "${1%%-*}" ] 2>/dev/null && return 0 || return 1
 }
 
-conf_rule_add() {
+upnpd_add_custom_acl_entry() {
 	local cfg="$1"
-	local action int_addr
-	local ext_start ext_end int_start int_end comment
-	config_get action "$cfg" action "deny"                # allow or deny
-	upnpd_get_port_range "ext" "$cfg" ext_ports "0-65535" # external ports: x, x-y, x:y
-	config_get int_addr "$cfg" int_addr "0.0.0.0/0"       # ip or network and subnet mask (internal)
-	upnpd_get_port_range "int" "$cfg" int_ports "0-65535" # internal ports: x, x-y, x:y or range
-	config_get comment "$cfg" comment "ACL"		      # comment
-
-	# Make a single IP IP/32 so that miniupnpd.conf can use it.
-	[ "${int_addr%/*}" = "$int_addr" ] && int_addr="$int_addr/32"
-
-	echo "$action $ext_start${ext_end:+-}$ext_end $int_addr $int_start${int_end:+-}$int_end #$comment"
+	local comment int_addr int_port ext_port descr_filter action
+	config_get comment "$cfg" comment "unspecified" # comment
+	config_get int_addr "$cfg" int_addr "0.0.0.0/0" # IPv4 or network and subnet mask (internal)
+	config_get int_port "$cfg" int_port "1-65535"   # internal port/range: x or x-y
+	config_get ext_port "$cfg" ext_port "1-65535"   # external port/range: x or x-y
+	config_get descr_filter "$cfg" descr_filter     # description regex filter (must be built in)
+	config_get action "$cfg" action                 # accept/reject/ignore
+	! is_port_or_range "$int_port" port0inrange &&
+		log "Custom ACL: Entry with invalid port or port range ($int_port) in int_port ignored" daemon.warn && int_port=1-65535
+	! is_port_or_range "$ext_port" port0inrange &&
+		log "Custom ACL: Entry with invalid port or port range ($ext_port) in ext_port ignored" daemon.warn && ext_port=1-65535
+	[ "$descr_filter" != "" ] && descr_filter=" \"$descr_filter\""
+	[ "$action" = "accept" ] && action=allow
+	[ "$action" = "reject" ] && action=deny
+	[ "$action" = "ignore" ] && return 0
+	[ "$action" = "" ] && log "Custom ACL: Entry with no action ignored" daemon.warn && return 0
+	echo "$action $ext_port $int_addr $int_port${descr_filter} # $comment"
 }
 
 upnpd() {
@@ -184,8 +180,9 @@ upnpd() {
 		# Enabled internal networks / access control
 		config_foreach upnpd_add_int_network_and_preset internal_network precustom
 		echo "# Custom ACL"
-		config_foreach conf_rule_add perm_rule
+		config_foreach upnpd_add_custom_acl_entry acl_entry
 		config_foreach upnpd_add_int_network_and_preset internal_network postcustom
+		echo "deny 1-65535 0.0.0.0/0 1-65535 # Reject ACL by default"
 
 		} > "$tmpconf"
 	fi
@@ -257,18 +254,8 @@ upnpd_add_int_network_and_preset() {
 	[ "$subnet" = "" ] && log "Cannot get IPv4 subnet for network $interface, access_preset ignored" daemon.warn && return 0
 	if [ "$2" = "precustom" ]; then
 		for rejectport in $reject_ports; do
-			if [ "$rejectport" -ge "1" ] 2>/dev/null && [ "$rejectport" -le "65535" ] 2>/dev/null ||
-				{
-					[ "${rejectport%%-*}" -ge "1" ] 2>/dev/null &&
-						[ "${rejectport%%-*}" -le "65535" ] 2>/dev/null &&
-						[ "${rejectport##*-}" -ge "1" ] 2>/dev/null &&
-						[ "${rejectport##*-}" -le "65535" ] 2>/dev/null &&
-						[ "${rejectport##*-}" -ge "${rejectport%%-*}" ] 2>/dev/null
-				}; then
-				echo "deny $rejectport $subnet $rejectport # Reject port $rejectport on $interface"
-			else
+			is_port_or_range "$rejectport" && echo "deny $rejectport $subnet $rejectport # Reject port $rejectport on $interface" ||
 				log "Invalid port or port range ($rejectport) in reject_ports ignored" daemon.warn
-			fi
 		done
 	fi
 	if { [ "$2" = "postcustom" ] && [ "$custom_acl_before" = "1" ]; } ||
@@ -285,18 +272,8 @@ upnpd_add_int_network_and_preset() {
 			log "Invalid access_preset ($access_preset) ignored" daemon.warn
 		fi
 		for acceptport in $acceptpresetports $accept_ports; do
-			if [ "$acceptport" -ge "1" ] 2>/dev/null && [ "$acceptport" -le "65535" ] 2>/dev/null ||
-				{
-					[ "${acceptport%%-*}" -ge "1" ] 2>/dev/null &&
-						[ "${acceptport%%-*}" -le "65535" ] 2>/dev/null &&
-						[ "${acceptport##*-}" -ge "1" ] 2>/dev/null &&
-						[ "${acceptport##*-}" -le "65535" ] 2>/dev/null &&
-						[ "${acceptport##*-}" -ge "${acceptport%%-*}" ] 2>/dev/null
-				}; then
-				echo "allow $acceptport $subnet $acceptport # Accept port $acceptport on $interface"
-			else
+			is_port_or_range "$acceptport" && echo "allow $acceptport $subnet $acceptport # Accept port $acceptport on $interface" ||
 				log "Invalid port or port range ($acceptport) in accept_ports ignored" daemon.warn
-			fi
 		done
 	fi
 	if [ "$2" = "precustom" ] && [ "$custom_acl_before" != "1" ] && [ "$access_preset" != "0" ]; then
@@ -439,6 +416,85 @@ upnpd_uci_migration() {
 		uci delete upnpd.config.notify_interval
 	fi
 
+	# Migrate custom ACL to new section, note that an empty ACL is now rejected alone
+	# a) Empty/unmodified ACL: Enable appropriate preset, add/update template entries
+	# b) Modified ACL:
+	#    - Add missing entry action to avoid adding inverted actions when changing via LuCI
+	#    - Update entry action allow/deny -> accept/reject
+	#    - Update entry port options to only use the LuCI (and daemon) supported hyphen (-) as port range separator
+	#    - Not using an preset, add template entries
+	! uci -q get upnpd.@acl_entry[0] >/dev/null && if ! uci -q get upnpd.@perm_rule[0] >/dev/null; then
+		log "Empty ACL: Enable preset, add templates, empty ACL now rejected alone"
+		access_preset=accept-all-ports
+		addtemplateentries=1
+	elif ! uci -q get upnpd.@perm_rule[2] >/dev/null &&
+		[ "$(uci -q get upnpd.@perm_rule[0].int_addr)" = "0.0.0.0/0" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[0].int_ports)" = "1024-65535" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[0].ext_ports)" = "1024-65535" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[0].action)" = "allow" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[1].int_addr)" = "0.0.0.0/0" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[1].int_ports)" = "0-65535" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[1].ext_ports)" = "0-65535" ] &&
+		[ "$(uci -q get upnpd.@perm_rule[1].action)" = "deny" ]; then
+		log "Unmodified ACL: Enable preset, update templates, empty ACL rejected"
+		access_preset=accept-high-ports
+		addtemplateentries=1
+		uci delete upnpd.@perm_rule[-1]
+		uci delete upnpd.@perm_rule[-1]
+	else
+		log "Modified ACL: Update ACL entry action/section, empty ACL now rejected"
+		access_preset=0
+		addtemplateentries=1
+		entrynr=0
+		while uci -q get upnpd.@perm_rule[$entrynr] >/dev/null; do
+			comment="$(uci -q get upnpd.@perm_rule[$entrynr].comment)"
+			int_addr="$(uci -q get upnpd.@perm_rule[$entrynr].int_addr)"
+			int_port="$(uci -q get upnpd.@perm_rule[$entrynr].int_ports)"
+			ext_port="$(uci -q get upnpd.@perm_rule[$entrynr].ext_ports)"
+			action="$(uci -q get upnpd.@perm_rule[$entrynr].action)"
+			echo "$int_port" | grep -q ":" &&
+				log "Modified ACL: Update entry int_port to only use a hyphen (-) as port range separator" &&
+				int_port="$(echo "$int_port" | tr ":" "-")"
+			echo "$ext_port" | grep -q ":" &&
+				log "Modified ACL: Update entry ext_port to only use a hyphen (-) as port range separator" &&
+				ext_port="$(echo "$ext_port" | tr ":" "-")"
+			[ "$action" = "" ] && log "Modified ACL: Add missing entry action" && action=reject
+			[ "$action" = "allow" ] && action=accept
+			[ "$action" = "deny" ] && action=reject
+			uci batch >/dev/null <<-EOF
+				add upnpd acl_entry
+				set upnpd.@acl_entry[-1].comment="${comment:-unspecified}"
+				set upnpd.@acl_entry[-1].int_addr="${int_addr:-0.0.0.0/0}"
+				set upnpd.@acl_entry[-1].int_port="$int_port"
+				set upnpd.@acl_entry[-1].ext_port="$ext_port"
+				set upnpd.@acl_entry[-1].action="$action"
+			EOF
+			entrynr=$((entrynr + 1))
+		done
+		[ "$int_addr" = "0.0.0.0/0" ] && [ "$int_port" = "0-65535" ] &&
+			[ "$ext_port" = "0-65535" ] && [ "$action" = "reject" ] &&
+			uci delete upnpd.@acl_entry[-1]
+		while uci -q delete upnpd.@perm_rule[-1]; do :; done
+	fi
+	if [ "$addtemplateentries" = "1" ]; then
+		uci batch >/dev/null <<-EOF
+			add upnpd acl_entry
+			add upnpd acl_entry
+			set upnpd.@acl_entry[-2].comment="High ports"
+			set upnpd.@acl_entry[-2].int_addr="0.0.0.0/0"
+			set upnpd.@acl_entry[-2].int_port="1024-65535"
+			set upnpd.@acl_entry[-2].ext_port="1024-65535"
+			set upnpd.@acl_entry[-2].action="ignore"
+			set upnpd.@acl_entry[-1].comment="Low/system ports"
+			set upnpd.@acl_entry[-1].int_addr="0.0.0.0/0"
+			set upnpd.@acl_entry[-1].int_port="1-1023"
+			set upnpd.@acl_entry[-1].ext_port="1-1023"
+			set upnpd.@acl_entry[-1].action="ignore"
+		EOF
+		uci -q get upnpd.@acl_entry[-3] >/dev/null &&
+			uci reorder upnpd.@acl_entry[-2]=0 && uci reorder upnpd.@acl_entry[-1]=1
+	fi
+
 	# Migrate internal_iface option to new internal_network section
 	if ! uci -q get upnpd.@internal_network[0] >/dev/null; then
 		ifnr=0
@@ -446,6 +502,7 @@ upnpd_uci_migration() {
 			log "Create new internal_network section for $interface"
 			uci add upnpd internal_network >/dev/null
 			uci set upnpd.@internal_network[$ifnr].interface="$interface"
+			[ "$access_preset" != "" ] && uci set upnpd.@internal_network[$ifnr].access_preset="$access_preset"
 			ifnr=$((ifnr + 1))
 		done
 		uci -q delete upnpd.config.internal_iface
